restart:
  - 'Monday;00;00' # Понедельник - 00:00 - МСК
  - 'Monday;12;00' # Понедельник - 12:00 - МСК
  - 'Tuesday;00;00' # Вторник - 00:00 - МСК
  - 'Tuesday;12;00' # Вторник - 12:00 - МСК
  - 'Wednesday;00;00' # Среда - 00:00 - МСК
  - 'Wednesday;12;00' # Среда - 12:00 - МСК
  - 'Thursday;00;00' # Четверг - 00:00 - МСК
  - 'Thursday;12;00' # Четверг - 12:00 - МСК
  - 'Friday;00;00' # Пятница - 00:00 - МСК
  - 'Friday;12;00' # Пятница - 12:00 - МСК
  - 'Saturday;00;00' # Суббота - 00:00 - МСК
  - 'Saturday;12;00' # Суббота - 12:00 - МСК
  - 'Sunday;00;00' # Воскресенье - 00:00 - МСК
  - 'Sunday;12;00' # Воскресенье - 12:00 - МСК

format:
  second: 'секунда'
  seconds: 'секунд'
  minute: 'минута'
  minutes: 'минут'
  hour: 'час'
  hours: 'часов'
  day: 'день'
  days: 'дней'